"""Base interface for all game effects."""
from abc import ABC
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..types import ObjectId

class Effect(ABC):
    """Base class for all effects generated by spells, abilities, or static abilities."""
    source_id: 'ObjectId' # Source of the effect (the GameObject)

    # Effects can be one-shot (applied immediately on resolution) or continuous.
    # This base class mainly identifies the source.
    # Subclasses (like ContinuousEffect) will add more properties.
    pass 